Ephemeral instances blog post
localstack/localstack-blog.github.io pull request #39
Opened 2024-08-08 21:22 UTC by remotesynth

This has the draft for the blog post announcing the preview availability of ephemeral instances. I need a banner image but otherwise it is ready to review.

2024-08-16 15:25 UTC, lukqw reviewed
Great job on the blog post @remotesynth!
I like the fun spin you took on it :) 

I've added a few remarks on where I think we can improve the wording / left a few suggestions and ideas we might want to incorporate before shipping it.

2024-08-16 15:25 UTC, lukqw commented on content/2024-08-12-ephemeral-instances/index.md
> +## Add an Application Preview after Commits
```suggestion
## Add automatic Application Previews to your Pull requests
```

2024-08-16 15:25 UTC, lukqw commented on content/2024-08-12-ephemeral-instances/index.md
> +The key element to understand is the `preview-cmd`, which runs all the steps that are required to build and deploy your application. As you can see below, this application needs the CDK as well as so
```suggestion
The key element to understand is the `preview-cmd`, which runs all the steps that are required to build and deploy your application. As you can see below, this application needs CDK as well as some npm dependencies installed before it can deploy the code to the ephemeral instance. It then adds a comment to the pull request with the preview URL (note that we are using `awslocal` to get the CloudFront distribution ID and overriding the preview URL with the URL to access this distribution).
```

2024-08-16 15:25 UTC, lukqw commented on content/2024-08-12-ephemeral-instances/index.md
> +This workflow is set to run on any PR and will add a comment to the PR with the preview running on a LocalStack instance automatically.
```suggestion
This workflow is set to run on any PR and will add a comment to the PR with the preview running on a LocalStack instance automatically.
Furthermore, each commit pushed to the PR will supersede the previous application preview, to ensure it's up to date.
```

2024-08-16 15:25 UTC, lukqw commented on content/2024-08-12-ephemeral-instances/index.md
> +It's important to note that the steps in the `preview-cmd` are run _after_ the ephemeral instance is created. Therefore, the ephemeral instance exists even if the steps fail. You can always go to the
should we add a sample here on how to shut down an instance?
We could nudge people to always perform the shut down action in case the preview-cmd fails for example.

2024-08-16 15:25 UTC, lukqw commented on content/2024-08-12-ephemeral-instances/index.md
> +But this is just the beginning. Ephemeral instances are only in the early public preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from yo
```suggestion
But this is just the beginning. Ephemeral instances are still in the early public preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from you. Give them a try and let us know what you think and share any ideas you may have for how we might make them even more valuable for you. You can always share feedback via our [community Slack]([localstack.cloud/slack](https://localstack.cloud/slack)).
```

2024-08-16 15:36 UTC, HarshCasper requested changes
On a high-level, I would suggest to:

1. Use bold for UI elements.
2. Have consistent terminology for product features. Eg: "Ephemeral Instances" vs "ephemeral instance(s)" and "Cloud Pods" vs "cloud pod".
3. Have a bit more description in the image alt text for accessibility. 
4. It seems we are using both Markdown-style image embeds and HTML/Hugo-style image tags. It would be great to stick with one style, with my preference being the later.

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +lead: We're excited to announce a preview of Ephemeral Instances. This new capability of LocalStack enables developers to quickly spin up a temporary LocalStack instance running in the cloud for thin
I would suggest to keep the description and lead the same. Let me know your thoughts 🤔

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +lastmod: 2024-08-12
Lets keep a note that this needs to be updated before the blog is merged!

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +---
Should we add weight to this blog and re-order the previous ones?

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +---
Let's also add the `show_cta_1: true` so that interested folks can connect with us if they're interested in using this feature.

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +But this is just the beginning. Ephemeral instances are only in the early public preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from yo
```suggestion
But this is just the beginning. Ephemeral instances are only in the preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from you. Give them a try and let us know what you think and share any ideas you may have for how we might make them even more valuable for you. You can always share feedback via our [community Slack]([localstack.cloud/slack](https://localstack.cloud/slack)).
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +But this is just the beginning. Ephemeral instances are only in the early public preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from yo
The Slack link is wrong and leads to a 404 page.

```suggestion
But this is just the beginning. Ephemeral instances are only in the early public preview stage and we have a lot of ideas for how to take this feature even further, but we'd also love to hear from you. Give them a try and let us know what you think and share any ideas you may have for how we might make them even more valuable for you. You can always share feedback via our [community Slack](https://localstack.cloud/slack).
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +![I'm glad we're right back where we started](back-where-we-started.gif)
Can we take a slightly better quality of the GIF and possibly align it in the middle?

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Well, we released a preview of a new feature called [ephemeral instances](https://docs.localstack.cloud/user-guide/cloud-sandbox/ephemeral-instance/) that does just that. Stick with me though, becaus
For features, I would suggest using caps in the way: **Ephemeral Instances**

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +* **Validating and Previewing Cloud Pods** – [Cloud pods](https://docs.localstack.cloud/user-guide/state-management/cloud-pods/) are a tool that enables you to capture a persistent state snapshot of
```suggestion
* **Validating and Previewing Cloud Pods** – [Cloud pods](https://docs.localstack.cloud/user-guide/state-management/cloud-pods/) is a tool that enables you to capture a persistent state snapshot of your LocalStack instance that can be restored and even shared. Ephemeral instances allow you to instantly spin up any Cloud Pod (or even any version of a Cloud Pod) for quick testing and validation.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +_Note: Ephemeral instances are in an early public preview. We'd love for you to try them out and give us your feedback, but, as this is an early preview release, you can expect some rough edges._
```suggestion
_Note: Ephemeral Instances is in public preview. We'd love for you to try them out and give us your feedback, but, as this is an early preview release, you can expect some rough edges._
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Manually creating a new ephemeral instance can be done via the LocalStack web app by navigating to *LocalStack Instances > [Ephemeral Instances](https://app.localstack.cloud/instances/ephemeral)* on
Can we make it bold since it signifies a UI element?

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +5. Optionally, you can choose any [extensions](https://docs.localstack.cloud/user-guide/extensions/extensions-library/) that you might want to have installed on the instance.
```suggestion
5. Optionally, you can choose any [extensions](https://app.localstack.cloud/extensions/library) that you might want to have installed on the instance.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +4. If you'd like to build your instance off of one of your existing Cloud Pods, you can choose it (we'll also explore another option to do this later in this article). If you don't choose one, the in
```suggestion
4. If you'd like to build your instance off of one of your existing Cloud Pods, you can choose it (we'll also explore another option to do this later in this article). If you don't choose one, the instance will start a fresh LocalStack container with no existing resources.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Hit the "Launch" button and give it a couple minutes to work its magic.
```suggestion
Hit the **Launch** button and give it a couple minutes to work its magic.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +### Adding Services to a Running Instance
```suggestion
### Adding resources to a Running Instance
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +The easiest way to add and manage services running on your ephemeral instance is via the web app. Once the instance is finished deploying, you should see it listed under your LocalStack Instances on
```suggestion
The easiest way to add and manage resources running on your ephemeral instance is via the web app. Once the instance is finished deploying, you should see it listed under your LocalStack Instances on the left hand navigation and also listed on the ephemeral instances page.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +If you choose the resource browser, you can add any of the services supported on your account to the running instance. For example, click on S3 and then, on the subsequent page, choose "Create." You'
```suggestion
If you choose the resource browser, you can add any of the services supported on your account to the running instance. For example, click on S3 and then, on the subsequent page, choose **Create**. You'll need to complete the bucket details via the form. At a minimum, choose a canned Access Control List (ACL) and a name. Once you submit the form, you should see your bucket created on the ephemeral instance.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +```bash
Can we add a step where we can export the `AWS_ENDPOINT_URL` and use `awslocal` rather than having a user to change the command and make it work?

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Once you have all your services and state set, you can click the "State" tab for your instance and save the state locally or to a Cloud Pod.
```suggestion
Once you have all your services and state set, you can click the **State** tab for your instance and save the state locally or to a Cloud Pod.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Creating all the services in your ephemeral instance manually probably isn't the ideal way to work, in part because you are consuming minutes as you do so and, depending on how long you chose for you
```suggestion
Creating all the resources in your ephemeral instance manually probably isn't the ideal way to work, in part because you are consuming minutes as you do so and, depending on how long you chose for your instance to live, there's also a chance it shuts down before you are done. Instead, it is better to use your local version of LocalStack running on Docker and then use one of the options LocalStack provides for [state management](https://docs.localstack.cloud/user-guide/state-management/) to save the state and load your state into a new ephemeral instance. Let's see how to do that using Cloud Pods.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +* **Collaboration** – LocalStack already made iteration and testing easy, but the only direct way to share the state of your work previously was to deploy it to AWS. This can require spinning up (and
```suggestion
* **Collaboration** – LocalStack already made iteration and testing easy, but the only direct way to share the state of your work previously was to deploy it to AWS. This can require spinning up (and then removing) a bunch of resources. Ephemeral instances make it easy to share a fully-functional, running instance of your code via just a link, while also making cleanup trivial.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +The easiest and most efficient way to create an ephemeral instance is via a [Cloud Pod](https://docs.localstack.cloud/user-guide/state-management/cloud-pods/). Cloud Pods are essentially a snapshot o
```suggestion
The easiest and most efficient way to create an ephemeral instance is via a [Cloud Pod](https://docs.localstack.cloud/user-guide/state-management/cloud-pods/). Cloud Pods are essentially a snapshot of the state of a running LocalStack instance that can be stored, versioned, shared, and restored. This means that, rather than creating a new empty ephemeral instance, you can create the ephemeral instance with the resources or data already deployed.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Once the application is running locally, the next step is to save the state into a Cloud Pod. In the command below, I am saving this to a new Cloud Pod that I am naming `brian-ephemeral-instance`.
Can we use commands without any PIIs so that the users can follow along without much changes needed?

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +Back in the LocalStack web app, I have several options for loading this instance into an ephemeral instance. For example, I can go directly to the Cloud Pods item on the left-hand navigation, click i
```suggestion
Back in the LocalStack web app, I have several options for loading this instance into an ephemeral instance. For example, I can go directly to the Cloud Pods item on the left-hand navigation, click into the detail page for my `brian-ephemeral-instance` pod and simply click on the **Browse Version** button to create a new instance using the currently selected version of the Cloud Pod that will live for 30 minutes.
```

2024-08-16 15:36 UTC, HarshCasper commented on content/2024-08-12-ephemeral-instances/index.md
> +The workflow below starts by checking the code that we want to deploy out of the repository. Next it uses the Setup LocalStack GitHub Action to start an ephemeral instance. I will need a legacy [Loca
Right now, new users cannot get legacy API keys. @lukqw any workarounds?

2024-08-21 14:32 UTC, remotesynth commented
> On a high-level, I would suggest to:
> 
> 1. Use bold for UI elements.
> 2. Have consistent terminology for product features. Eg: "Ephemeral Instances" vs "ephemeral instance(s)" and "Cloud Pods" vs "cloud pod".
> 3. Have a bit more description in the image alt text for accessibility.
> 4. It seems we are using both Markdown-style image embeds and HTML/Hugo-style image tags. It would be great to stick with one style, with my preference being the later.

1. Ok. Done.
2. Makes sense for Cloud Pod which is a unique feature to LocalStack. Since an ephemeral instance is a thing and not just a product, I'm going to leave references to an ephemeral instance as lowercase but references to the feature in the product like where I say to open the navigation and such, as uppercase.
3. Yup. Done.
4. Going to leave these alone as those images don't need resizing and we may have to remove shortcode references in the near future.

2024-08-21 18:53 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +Once the application is running locally, the next step is to save the state into a Cloud Pod. In the command below, I am saving this to a new Cloud Pod that I am naming `brian-ephemeral-instance`.
In this case, they'd still have to replace whatever name placeholder I put (ex. `<cloud pod name>`), which I am not sure is clearer.

2024-08-21 20:41 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +title: Local Testing in the Cloud with Ephemeral Instances
This was me trying to be clever by playing on the local in the cloud aspect that is contradictory but I think it needed some work. I tweaked it some.

2024-08-21 20:41 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +It's important to note that the steps in the `preview-cmd` are run _after_ the ephemeral instance is created. Therefore, the ephemeral instance exists even if the steps fail. You can always go to the
I left that for the docs. I think it may be too much detail for a post that is trying to pitch the concept.

2024-08-22 17:43 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +2. Choose LocalStack AWS or the new preview of [LocalStack Snowflake](https://blog.localstack.cloud/2024-05-22-introducing-localstack-for-snowflake/).
Removed.

2024-08-22 17:50 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +Well, we released a preview of a new feature called [ephemeral instances](https://docs.localstack.cloud/user-guide/cloud-sandbox/ephemeral-instance/) that does just that. Stick with me though, becaus
Changed

2024-08-22 18:01 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +4. If you'd like to build your instance off of one of your existing Cloud Pods, you can choose it (we'll also explore another option to do this later in this article). If you don't choose one, the in
Fixed

2024-08-22 18:30 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +```bash
Done

2024-08-28 12:11 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +lastmod: 2024-08-12
Date updated

2024-08-28 12:11 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +The workflow below starts by checking the code that we want to deploy out of the repository. Next it uses the Setup LocalStack GitHub Action to start an ephemeral instance. I will need a legacy [Loca
Changed to CI key

2024-08-28 12:20 UTC, remotesynth commented on content/2024-08-12-ephemeral-instances/index.md
> +If you choose the resource browser, you can add any of the services supported on your account to the running instance. For example, click on S3 and then, on the subsequent page, choose "Create." You'
Good point. Fixed.

2024-08-28 12:53 UTC, HarshCasper approved these changes

2024-08-28 12:55 UTC, merged