add blog on infra testing with cloud pods
localstack/localstack-blog.github.io pull request #40
Opened 2024-08-21 10:55 UTC by HarshCasper

2024-08-26 08:53 UTC, giograno approved these changes
Great blog post! Nothing major to add 💯

2024-08-26 17:36 UTC, remotesynth requested changes
Great stuff! This seems like a really useful example of something that really shows the value of LocalStack beyond just emulation. I think the intro could be a bit stronger in that sense. The value here is in the capabilities that saving state to cloud pods enables rather than in the act of saving state, if that makes sense.

2024-08-26 17:36 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +This blog will guide you in creating a Cloud Pod for your CDK stack, making infrastructure testing faster and more efficient. Additionally, we'll discuss using Cloud Pods to pre-seed your continuous
This is a good intro but I think it doesn't hit the exact nature of this post which takes this a step beyond just saving the state into integrating that saved state in a CI workflow that enables you to test against an ephemeral environment with the full state necessary to conduct that testing.

2024-08-26 17:36 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +Step Functions control the sequence of activities and transfer data between components for the Loan Broker, while Lambda functions implement the business logic for the Loan Broker, Banks, and Aggrega
It would be The step function controls...

2024-08-26 17:36 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +All resources can be deployed using the Cloud Development Kit (CDK). Before configuring the GitHub Action workflow, you need to save the infrastructure state using Cloud Pods on your local machine. A
This sounded to me like you are giving instructions rather than laying out the steps you'll follow in the guide. It's part of why I tend towards "we" instead of "you" because it sounds less like a command but in this case I think it's also the tense that makes it sound like something you are expecting us to do.

> All resources will be deployed using the Cloud Development Kit (CDK). Before configuring the GitHub Action workflow, we'll need to save the infrastructure state using Cloud Pods on our local machine. After saving the Cloud Pod as a persistent state snapshot, we'll be able toimplement a workflow that injects the Cloud Pod into our GitHub Action runner. Let's walk through the steps.

2024-08-26 17:36 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +> Customize the account ID and region values for multi-account and multi-region setups in LocalStack.
Should this say "You can customize..."?

2024-08-26 17:36 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +An interesting note is that it's faster to save your pre-existing infrastructure into a Cloud Pod, which can be further used for testing, compared to spinning up your infrastructure from scratch usin
the CDK

2024-08-29 21:05 UTC, remotesynth commented on content/2024-08-21-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +This blog will guide you in creating a Cloud Pod for your CDK stack, making infrastructure testing faster and more efficient. Additionally, we'll discuss using Cloud Pods to pre-seed your continuous
Here's an attempt to rewrite this but with a bit more focus on the key aspect of the post, which is the testing. I tried to keep the salient points in the current into in, but be more concise and get them to the key pitch which is about CI testing.

> LocalStack is a cloud service emulator that lets you develop and test cloud applications locally. As a Docker image, it’s ephemeral—any local cloud resources like S3 buckets or Lambda functions are destroyed when you stop the container.
>
> This is exactly what you need for testing CDK, Terraform, or CloudFormation deployments, but there are cases where saving, restoring, and sharing LocalStack's state is important. That’s where LocalStack's Cloud Pods come in.
>
> Cloud Pods are snapshots of your LocalStack’s state that are stored on the LocalStack Web Application. This is incredibly useful for things like:
>
> 1. Ensuring consistent developer environments and easing onboarding.
> 2. Reducing environment setup times.
> 3. Creating specific automated testing scenarios for your application.
>
> In this post, we're going to focus into this third use case: using Cloud Pods to enable pre-seeded testing scenarios in continuous integration (CI) processes. We’ll explore creating a Cloud Pod from an existing stack, implementing integration tests against LocalStack, and adding these tests to a CI workflow using GitHub Actions.

2024-09-17 19:34 UTC, gtsiolis reviewed
Great content, @HarshCasper! 💛

Left some minor non-blocking comments.

I enjoyed reading this! 😃 

One question to ask ourselves here is whether this fits more as a tutorial rather than a blog post.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +images: ['accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions-cover.png']
**praise**: Great header image. Is this @lazarvu magic? 🔮

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +description: Cloud pods are persistent state snapshots of your LocalStack container. This blog guide you to use LocalStack Cloud Pods to save and load infrastructure state, enabling faster, consisten
**nitpick**: It would be nice if we could add some links to the docs to core features like cloud pods. I understand this is not part of the main markdown text though here.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +Cloud Pods are snapshots of your LocalStack’s state that are stored on the LocalStack Web Application. This is incredibly useful for things like:
**question**: Could it be more accurate to say stored in the LocalStack _Cloud_, not the _Web Application_? I understand this may be a new term though, but food for thoughts. 🍔

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +## Table of Contents
**thought**: Having a Toc here makes me think, is this a blog post or a tutorial?

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +## Tutorial: Loan Broker application with Step Functions, DynamoDB and Lambda
**nitpick**: I haven't seen any content guidelines but using a serial comma here could be nice. Something to consider onwards. 🍔

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +This demo utilizes a [**public sample**](https://github.com/localstack-samples/sample-loan-broker-stepfunctions-lambda) to showcase a Loan Broker application inspired by Gregor Hohpe's [Loan Broker e
**issue(non-blocking)**: The link color is quite subtle and barely noticeable. I guess this will be better with the blog redesign, but worth bringing it up here for visibility.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +-   User submits a loan application with personal data, desired terms, loan amount, and duration.
**nitpick**: Could be nice to have an ordered list here since this describes a sequence.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +localstack auth set-token <your-auth-token>
**praise**: Thank you for using the auth CLI command instead of the variable here. 😃

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +curl -X GET http://localhost:4566/_localstack/info | jq
**question**: Is this a more reliable way than the license CLI command?

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +### Set Up the infrastructure locally
**nitpick**: Minor typo, _Set up_...

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +To begin, fork the LocalStack sample repository on GitHub using this command:
**issue(non-blocking)**: Is the fort needed here? If so, it could be more accurate to update the clone command to use the fork.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +> You can customize the account ID and region values for multi-account and multi-region setups in LocalStack.
**question**: Using the callout here sounds unnecessary, no?

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +To create a Cloud Pod, utilize the `pods` CLI, which is shipped alongside the LocalStack CLI. Ensure the LocalStack CLI experience is activated by specifying `LOCALSTACK_AUTH_TOKEN` in the environmen
**nitpick**: Minor typo, the `pod` CLI command.

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +localstack restart
**thought**: TIL about the `restart` CLI command. 💡

2024-09-17 19:34 UTC, gtsiolis commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +1.  Go to the [LocalStack Web Application](https://app.localstack.cloud/) and access the [CI Keys](https://app.localstack.cloud/workspace/ci-keys) page.
**praise**: Thanks for using an ordered list here. 💯

2024-09-18 06:50 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +> You can customize the account ID and region values for multi-account and multi-region setups in LocalStack.
Yes, agreed with that 👍

2024-09-18 06:55 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +curl -X GET http://localhost:4566/_localstack/info | jq
If the Auth Token is not valid or available this allows to give the users a quick validation. I primarily added because the tutorial won't work for Community/Starter/Hobby tier.

2024-09-18 07:09 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +images: ['accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions-cover.png']
Yeah 😄

2024-09-18 07:09 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +description: Cloud pods are persistent state snapshots of your LocalStack container. This blog guide you to use LocalStack Cloud Pods to save and load infrastructure state, enabling faster, consisten
Adding links here would break the frontmatter and mess up with our SEO.

2024-09-18 07:15 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +## Table of Contents
Its a tutorial. As a developer, I really appreciate having a ToC so that I can jump between sections and give it a very quick read. The blog in itself is pretty long (over a 10 minutes read), hence a ToC would make sense to have.

2024-09-18 07:22 UTC, HarshCasper commented on content/2024-09-17-accelerate-infrastructure-testing-with-localstack-cloud-pods-github-actions/index.md
> +To begin, fork the LocalStack sample repository on GitHub using this command:
Yes, its now updated!

2024-09-18 12:59 UTC, remotesynth approved these changes

2024-09-19 08:44 UTC, merged